### ISSUE TITLE
BUG - Mock Server for oData V4

### ISSUE THREAD

**Issue by aliaksei-dunets-public** [SAP/open-ux-odata#749]
Hello, 
I've detected the issue with MockServer for oData v4 (CAP) for a SAPUI5 App. 

"devDependencies": {
"@sap-ux/ui5-middleware-fe-mockserver": "^2.2.6"
},
"ui5": {
"dependencies": [
"@sap/ui5-builder-webide-extension",
"@sap-ux/ui5-middleware-fe-mockserver",
]
}

I have an OData V4 (CAP) service call with the path: /Header?$filter=formats/any(f:f/FORMAT_ID eq 1) and not items/any().
This request works fine with real OData call and without a filter option without "not", but when I try to trigger it via a Mock server there is an error: Cannot read properties of undefined (reading 'operator')

Error stack:
info server:ux-fe-mockserver ODataRequest: GET /Header?$filter=formats/any(f:f/STORE_FORMAT_ID%20eq%201)%20and%20not%20items/any()
ERR! server:ux-fe-mockserver TypeError: Cannot read properties of undefined (reading 'operator')
ERR! server:ux-fe-mockserver at FilterParser.ALT (/home/user/projects/shelf-survey/app/shelfsurvey/node_modules/@sap-ux/fe-mockserver-core/dist/request/filterParser.js:223:50)
ERR! server:ux-fe-mockserver at RecognizerEngine.orInternal (/home/user/projects/shelf-survey/app/shelfsurvey/node_modules/chevrotain/lib/src/parse/parser/traits/recognizer_engine.js:400:42)
ERR! server:ux-fe-mockserver at RecognizerApi.OR (/home/user/projects/shelf-survey/app/shelfsurvey/node_modules/chevrotain/lib/src/parse/parser/traits/recognizer_api.js:133:21)
ERR! server:ux-fe-mockserver at FilterParser. (/home/user/projects/shelf-survey/app/shelfsurvey/node_modules/@sap-ux/fe-mockserver-core/dist/request/filterParser.js:208:29)
ERR! server:ux-fe-mockserver at FilterParser.invokeRuleWithTry (/home/user/projects/shelf-survey/app/shelfsurvey/node_modules/chevrotain/lib/src/parse/parser/traits/recognizer_engine.js:118:33)
ERR! server:ux-fe-mockserver at FilterParser.wrappedGrammarRule [as boolCommonExpr] (/home/user/projects/shelf-survey/app/shelfsurvey/node_modules/chevrotain/lib/src/parse/parser/traits/recognizer_engine.js:131:38)
ERR! server:ux-fe-mockserver at RecognizerEngine.subruleInternal (/home/user/projects/shelf-survey/app/shelfsurvey/node_modules/chevrotain/lib/src/parse/parser/traits/recognizer_engine.js:422:37)
ERR! server:ux-fe-mockserver at RecognizerApi.SUBRULE2 (/home/user/projects/shelf-survey/app/shelfsurvey/node_modules/chevrotain/lib/src/parse/parser/traits/recognizer_api.js:79:21)
ERR! server:ux-fe-mockserver at FilterParser. (/home/user/projects/shelf-survey/app/shelfsurvey/node_modules/@sap-ux/fe-mockserver-core/dist/request/filterParser.js:266:38)
ERR! server:ux-fe-mockserver at RecognizerEngine.optionInternalLogic (/home/user/projects/shelf-survey/app/shelfsurvey/node_modules/chevrotain/lib/src/parse/parser/traits/recognizer_engine.js:212:27)
ERR! server:ux-fe-mockserver TypeError: Cannot read properties of undefined (reading 'operator')
ERR! server:ux-fe-mockserver at FilterParser.ALT (/home/user/projects/shelf-survey/app/shelfsurvey/node_modules/@sap-ux/fe-mockserver-core/dist/request/filterParser.js:223:50)
ERR! server:ux-fe-mockserver at RecognizerEngine.orInternal (/home/user/projects/shelf-survey/app/shelfsurvey/node_modules/chevrotain/lib/src/parse/parser/traits/recognizer_engine.js:400:42)
ERR! server:ux-fe-mockserver at RecognizerApi.OR (/home/user/projects/shelf-survey/app/shelfsurvey/node_modules/chevrotain/lib/src/parse/parser/traits/recognizer_api.js:133:21)
ERR! server:ux-fe-mockserver at FilterParser. (/home/user/projects/shelf-survey/app/shelfsurvey/node_modules/@sap-ux/fe-mockserver-core/dist/request/filterParser.js:208:29)
ERR! server:ux-fe-mockserver at FilterParser.invokeRuleWithTry (/home/user/projects/shelf-survey/app/shelfsurvey/node_modules/chevrotain/lib/src/parse/parser/traits/recognizer_engine.js:118:33)
ERR! server:ux-fe-mockserver at FilterParser.wrappedGrammarRule [as boolCommonExpr] (/home/user/projects/shelf-survey/app/shelfsurvey/node_modules/chevrotain/lib/src/parse/parser/traits/recognizer_engine.js:131:38)
ERR! server:ux-fe-mockserver at RecognizerEngine.subruleInternal (/home/user/projects/shelf-survey/app/shelfsurvey/node_modules/chevrotain/lib/src/parse/parser/traits/recognizer_engine.js:422:37)
ERR! server:ux-fe-mockserver at RecognizerApi.SUBRULE2 (/home/user/projects/shelf-survey/app/shelfsurvey/node_modules/chevrotain/lib/src/parse/parser/traits/recognizer_api.js:79:21)
ERR! server:ux-fe-mockserver at FilterParser. (/home/user/projects/shelf-survey/app/shelfsurvey/node_modules/@sap-ux/fe-mockserver-core/dist/request/filterParser.js:266:38)
ERR! server:ux-fe-mockserver at RecognizerEngine.optionInternalLogic **(/home/user/projects/shelf-survey/app/shelfsurvey/node_modules/chevrotain/lib/src/parse/parser/traits/recognizer_engine.js:212:27)**

![image](https://github.com/SAP/open-ux-odata/assets/22812746/1c07cb41-f9a3-4705-949a-3eaa7ce02c7c)

**Comment by helencorrigan** [comment]
FYI @nlunets
