### ISSUE TITLE
BUG - pathRegexp.match is not a function

### ISSUE THREAD

**Issue by villa-vanilli** [SAP/open-ux-odata#897]
### Related Feature
@sap-ux/ui5-mockserver-core

### Description
We have following issue since PR https://github.com/SAP/open-ux-odata/pull/876 and the update to router 2.0.0.

When using @sap-ux/ui5-middleware-fe-mockserver and the configuration ui5.yaml the server cannot start.

### Steps to Reproduce
1. Start `ui5 serve --config ./ui5.yaml`
2. See stack trace
```
Error Message:
pathRegexp.match is not a function

Stack Trace:
TypeError: pathRegexp.match is not a function
    at matcher (../ui/node_modules/router/lib/layer.js:83:23)
    at new Layer (../ui/node_modules/router/lib/layer.js:90:62)
    at Function.route (../ui/node_modules/router/index.js:421:17)
    at Router.<computed> [as get] (../ui/node_modules/router/index.js:440:24)
    at catalogServiceRouter (../ui/node_modules/@sap-ux/fe-mockserver-core/dist/router/catalogServiceRouter.js:18:12)
    at prepareCatalogAndAnnotation (../ui/node_modules/@sap-ux/fe-mockserver-core/dist/middleware.js:65:104)
    at createMockMiddleware (../ui/node_modules/@sap-ux/fe-mockserver-core/dist/middleware.js:157:5)
    at FEMockserver.initialize (../ui/node_modules/@sap-ux/fe-mockserver-core/dist/index.js:47:53)
    at async FEMiddleware (../ui/node_modules/@sap-ux/ui5-middleware-fe-mockserver/dist/index.js:42:5)
    at async MiddlewareManager.addMiddleware (file://../ui/node_modules/@ui5/cli/node_modules/@ui5/server/lib/middleware/MiddlewareManager.js:121:16)
```

#### Version/Components/Environment	
Add any other context about the problem here
OS:                      
- [x] Mac OS
- [x] Windows

### Problem
{describe the problem} 

### Fix
{describe the fix} 

### Why was it missed
{Some explanation why this issue might have been missed during normal development/testing cycle}  

### How can we avoid this
{if we don’t want to see this type of issues anymore what we should do to prevent}

**Comment by nlunets** [comment]
Hello @villa-vanilli do you somehow force a resolutions for the `router` module ?
The fact that the method is missing is weird
